/*
 * This file is generated by jOOQ.
*/
package com.pubsub.project2.entity.tables.records;


import com.pubsub.project2.entity.tables.Publisher;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PublisherRecord extends UpdatableRecordImpl<PublisherRecord> implements Record5<Long, String, String, Byte, Long> {

    private static final long serialVersionUID = 570559340;

    /**
     * Setter for <code>pubsub_phase3.publisher.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>pubsub_phase3.publisher.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>pubsub_phase3.publisher.webhook_url</code>.
     */
    public void setWebhookUrl(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pubsub_phase3.publisher.webhook_url</code>.
     */
    public String getWebhookUrl() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pubsub_phase3.publisher.nick_name</code>.
     */
    public void setNickName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>pubsub_phase3.publisher.nick_name</code>.
     */
    public String getNickName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>pubsub_phase3.publisher.is_active</code>.
     */
    public void setIsActive(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>pubsub_phase3.publisher.is_active</code>.
     */
    public Byte getIsActive() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>pubsub_phase3.publisher.region_id</code>.
     */
    public void setRegionId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>pubsub_phase3.publisher.region_id</code>.
     */
    public Long getRegionId() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, String, Byte, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, String, Byte, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Publisher.PUBLISHER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Publisher.PUBLISHER.WEBHOOK_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Publisher.PUBLISHER.NICK_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field4() {
        return Publisher.PUBLISHER.IS_ACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return Publisher.PUBLISHER.REGION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getWebhookUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getNickName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component4() {
        return getIsActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getRegionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getWebhookUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getNickName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value4() {
        return getIsActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getRegionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PublisherRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PublisherRecord value2(String value) {
        setWebhookUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PublisherRecord value3(String value) {
        setNickName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PublisherRecord value4(Byte value) {
        setIsActive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PublisherRecord value5(Long value) {
        setRegionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PublisherRecord values(Long value1, String value2, String value3, Byte value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PublisherRecord
     */
    public PublisherRecord() {
        super(Publisher.PUBLISHER);
    }

    /**
     * Create a detached, initialised PublisherRecord
     */
    public PublisherRecord(Long id, String webhookUrl, String nickName, Byte isActive, Long regionId) {
        super(Publisher.PUBLISHER);

        set(0, id);
        set(1, webhookUrl);
        set(2, nickName);
        set(3, isActive);
        set(4, regionId);
    }
}
