/*
 * This file is generated by jOOQ.
*/
package com.pubsub.project2.entity.tables.records;


import com.pubsub.project2.entity.tables.Topic;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TopicRecord extends UpdatableRecordImpl<TopicRecord> implements Record3<Long, String, Byte> {

    private static final long serialVersionUID = 1058362618;

    /**
     * Setter for <code>pubsub_phase3.topic.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>pubsub_phase3.topic.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>pubsub_phase3.topic.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pubsub_phase3.topic.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pubsub_phase3.topic.is_deleted</code>.
     */
    public void setIsDeleted(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>pubsub_phase3.topic.is_deleted</code>.
     */
    public Byte getIsDeleted() {
        return (Byte) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, String, Byte> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, String, Byte> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Topic.TOPIC.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Topic.TOPIC.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field3() {
        return Topic.TOPIC.IS_DELETED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component3() {
        return getIsDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value3() {
        return getIsDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TopicRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TopicRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TopicRecord value3(Byte value) {
        setIsDeleted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TopicRecord values(Long value1, String value2, Byte value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TopicRecord
     */
    public TopicRecord() {
        super(Topic.TOPIC);
    }

    /**
     * Create a detached, initialised TopicRecord
     */
    public TopicRecord(Long id, String name, Byte isDeleted) {
        super(Topic.TOPIC);

        set(0, id);
        set(1, name);
        set(2, isDeleted);
    }
}
