/*
 * This file is generated by jOOQ.
*/
package com.pubsub.project2.entity;


import com.pubsub.project2.entity.tables.Message;
import com.pubsub.project2.entity.tables.Publisher;
import com.pubsub.project2.entity.tables.Region;
import com.pubsub.project2.entity.tables.Subscriber;
import com.pubsub.project2.entity.tables.Subscription;
import com.pubsub.project2.entity.tables.Topic;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>pubsub_phase3</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index MESSAGE_PRIMARY = Indexes0.MESSAGE_PRIMARY;
    public static final Index MESSAGE_PUBLISHER_ID = Indexes0.MESSAGE_PUBLISHER_ID;
    public static final Index MESSAGE_TOPIC_ID = Indexes0.MESSAGE_TOPIC_ID;
    public static final Index PUBLISHER_PRIMARY = Indexes0.PUBLISHER_PRIMARY;
    public static final Index PUBLISHER_REGION_ID = Indexes0.PUBLISHER_REGION_ID;
    public static final Index REGION_PRIMARY = Indexes0.REGION_PRIMARY;
    public static final Index SUBSCRIBER_PRIMARY = Indexes0.SUBSCRIBER_PRIMARY;
    public static final Index SUBSCRIBER_REGION_ID = Indexes0.SUBSCRIBER_REGION_ID;
    public static final Index SUBSCRIPTION_PRIMARY = Indexes0.SUBSCRIPTION_PRIMARY;
    public static final Index SUBSCRIPTION_SUBSCRIBER_ID = Indexes0.SUBSCRIPTION_SUBSCRIBER_ID;
    public static final Index SUBSCRIPTION_TOPIC_ID = Indexes0.SUBSCRIPTION_TOPIC_ID;
    public static final Index TOPIC_PRIMARY = Indexes0.TOPIC_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index MESSAGE_PRIMARY = Internal.createIndex("PRIMARY", Message.MESSAGE, new OrderField[] { Message.MESSAGE.ID }, true);
        public static Index MESSAGE_PUBLISHER_ID = Internal.createIndex("publisher_id", Message.MESSAGE, new OrderField[] { Message.MESSAGE.PUBLISHER_ID }, false);
        public static Index MESSAGE_TOPIC_ID = Internal.createIndex("topic_id", Message.MESSAGE, new OrderField[] { Message.MESSAGE.TOPIC_ID }, false);
        public static Index PUBLISHER_PRIMARY = Internal.createIndex("PRIMARY", Publisher.PUBLISHER, new OrderField[] { Publisher.PUBLISHER.ID }, true);
        public static Index PUBLISHER_REGION_ID = Internal.createIndex("region_id", Publisher.PUBLISHER, new OrderField[] { Publisher.PUBLISHER.REGION_ID }, false);
        public static Index REGION_PRIMARY = Internal.createIndex("PRIMARY", Region.REGION, new OrderField[] { Region.REGION.ID }, true);
        public static Index SUBSCRIBER_PRIMARY = Internal.createIndex("PRIMARY", Subscriber.SUBSCRIBER, new OrderField[] { Subscriber.SUBSCRIBER.ID }, true);
        public static Index SUBSCRIBER_REGION_ID = Internal.createIndex("region_id", Subscriber.SUBSCRIBER, new OrderField[] { Subscriber.SUBSCRIBER.REGION_ID }, false);
        public static Index SUBSCRIPTION_PRIMARY = Internal.createIndex("PRIMARY", Subscription.SUBSCRIPTION, new OrderField[] { Subscription.SUBSCRIPTION.ID }, true);
        public static Index SUBSCRIPTION_SUBSCRIBER_ID = Internal.createIndex("subscriber_id", Subscription.SUBSCRIPTION, new OrderField[] { Subscription.SUBSCRIPTION.SUBSCRIBER_ID }, false);
        public static Index SUBSCRIPTION_TOPIC_ID = Internal.createIndex("topic_id", Subscription.SUBSCRIPTION, new OrderField[] { Subscription.SUBSCRIPTION.TOPIC_ID }, false);
        public static Index TOPIC_PRIMARY = Internal.createIndex("PRIMARY", Topic.TOPIC, new OrderField[] { Topic.TOPIC.ID }, true);
    }
}
