/*
 * This file is generated by jOOQ.
*/
package com.pubsub.project2.entity;


import com.pubsub.project2.entity.tables.Message;
import com.pubsub.project2.entity.tables.Publisher;
import com.pubsub.project2.entity.tables.Region;
import com.pubsub.project2.entity.tables.Subscriber;
import com.pubsub.project2.entity.tables.Subscription;
import com.pubsub.project2.entity.tables.Topic;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in pubsub_phase3
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>pubsub_phase3.message</code>.
     */
    public static final Message MESSAGE = com.pubsub.project2.entity.tables.Message.MESSAGE;

    /**
     * The table <code>pubsub_phase3.publisher</code>.
     */
    public static final Publisher PUBLISHER = com.pubsub.project2.entity.tables.Publisher.PUBLISHER;

    /**
     * The table <code>pubsub_phase3.region</code>.
     */
    public static final Region REGION = com.pubsub.project2.entity.tables.Region.REGION;

    /**
     * The table <code>pubsub_phase3.subscriber</code>.
     */
    public static final Subscriber SUBSCRIBER = com.pubsub.project2.entity.tables.Subscriber.SUBSCRIBER;

    /**
     * The table <code>pubsub_phase3.subscription</code>.
     */
    public static final Subscription SUBSCRIPTION = com.pubsub.project2.entity.tables.Subscription.SUBSCRIPTION;

    /**
     * The table <code>pubsub_phase3.topic</code>.
     */
    public static final Topic TOPIC = com.pubsub.project2.entity.tables.Topic.TOPIC;
}
