/*
 * This file is generated by jOOQ.
*/
package com.pubsub.project2.entity.tables;


import com.pubsub.project2.entity.Indexes;
import com.pubsub.project2.entity.Keys;
import com.pubsub.project2.entity.PubsubPhase3;
import com.pubsub.project2.entity.tables.records.RegionRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Region extends TableImpl<RegionRecord> {

    private static final long serialVersionUID = -1545458638;

    /**
     * The reference instance of <code>pubsub_phase3.region</code>
     */
    public static final Region REGION = new Region();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RegionRecord> getRecordType() {
        return RegionRecord.class;
    }

    /**
     * The column <code>pubsub_phase3.region.id</code>.
     */
    public final TableField<RegionRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>pubsub_phase3.region.name</code>.
     */
    public final TableField<RegionRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * Create a <code>pubsub_phase3.region</code> table reference
     */
    public Region() {
        this(DSL.name("region"), null);
    }

    /**
     * Create an aliased <code>pubsub_phase3.region</code> table reference
     */
    public Region(String alias) {
        this(DSL.name(alias), REGION);
    }

    /**
     * Create an aliased <code>pubsub_phase3.region</code> table reference
     */
    public Region(Name alias) {
        this(alias, REGION);
    }

    private Region(Name alias, Table<RegionRecord> aliased) {
        this(alias, aliased, null);
    }

    private Region(Name alias, Table<RegionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return PubsubPhase3.PUBSUB_PHASE3;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.REGION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RegionRecord, Long> getIdentity() {
        return Keys.IDENTITY_REGION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RegionRecord> getPrimaryKey() {
        return Keys.KEY_REGION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RegionRecord>> getKeys() {
        return Arrays.<UniqueKey<RegionRecord>>asList(Keys.KEY_REGION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Region as(String alias) {
        return new Region(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Region as(Name alias) {
        return new Region(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Region rename(String name) {
        return new Region(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Region rename(Name name) {
        return new Region(name, null);
    }
}
